@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":AddStudentCommandParser" as AddStudentCommandParser LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "a:AddStudentCommand" as AddStudentCommand LOGIC_COLOR
end box

-> AddStudentCommandParser : parse("n/john smith e/eg@eg.com t/john1 tg/CS2106 T04")
activate AddStudentCommandParser

AddStudentCommandParser -> ParserUtil : parseName("n/john smith")
activate ParserUtil

ParserUtil --> AddStudentCommandParser : n
deactivate ParserUtil

AddStudentCommandParser -> ParserUtil : parseEmail("e/eg@eg.com")
activate ParserUtil

ParserUtil --> AddStudentCommandParser : e
deactivate ParserUtil

AddStudentCommandParser -> ParserUtil : parseTelegram("t/john1")
activate ParserUtil

ParserUtil --> AddStudentCommandParser : t
deactivate ParserUtil

ParserUtil -> AddStudentCommandParser : parseGitHub(null)
activate ParserUtil

ParserUtil --> AddStudentCommandParser : g
deactivate ParserUtil

ParserUtil -> AddStudentCommandParser : parseTutorialGroup("CS2106 T04")
activate ParserUtil

ParserUtil --> AddStudentCommandParser : tg
deactivate ParserUtil

create AddStudentCommand
AddStudentCommandParser -> AddStudentCommand : new AddStudentCommandParser(n, e, t, g, tg)
activate AddStudentCommand

AddStudentCommand --> AddStudentCommandParser : d
deactivate AddStudentCommand

[<--AddStudentCommandParser
deactivate AddStudentCommandParser
destroy AddStudentCommandParser
@enduml
