@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueStudentList
AddressBook *-right-> "1" UniqueTutorialList
UniqueTutorialList -[hidden]down- UniqueStudentList
UniqueTutorialList -[hidden]down- UniqueStudentList

UniqueTutorialList *-right-> "*" TutorialGroup
UniqueStudentList -right-> "*" Student

Student -up-> "1..*" TutorialGroup

Student *--> "1" Name
Student *--> "0..1" Telegram
Student *--> "1" Email
Student *--> "0..1" GitHub
@enduml
